### ISSUE TITLE
Make ToDo-Groceries functional

### ISSUE THREAD

**Issue by emmanuelkiranr** [emmanuelkiranr/iCodeThis-Challenges#5]
- [ ] A model should appear to input the todo details while clicking [+] button
- [ ] The model should contain a input field and 2 buttons - Add and Cancel
- [ ] Add will add the todo item to the list
- [ ] Cancel will close the model
- [ ] Marking list items as complete should move them to the completed list
